### ISSUE TITLE
develop branch

### ISSUE THREAD

**Issue by aurpo1** [KDT-STFE-3-Team-2/Pig_the_Dice#10]
메인 저장소에도 develop branch가 있어야 하지 않을까요?!
PR 날리려다 main 밖에 없어서 제안 드립니다. 
이슈 한 번 더 써볼라고 작성해봤습니다. (하하)

**Comment by oaat9309** [comment]
github 상에서 develop 브랜치 만들었습니다! 
피드백 감사합니다...!
